"""Visual inverse-kinematics replay for one Microtaur five-bar leg.

The robot base is held fixed in the air.  A green mocap sphere marks the target
foot-site position.  The selected leg's two Dynamixel motor targets are
generated by the analytical five-bar IK solver.

By default, the motors move through the same approximate XL330 PD +
torque-speed model used by the training environment.  Pass --kinematic to
directly interpolate the motor qpos values for a pure geometry check.

Example:
  uv run --active --no-sync python replay_microtaur_ik.py --leg 1

Static target:
  uv run --active --no-sync python replay_microtaur_ik.py \
    --leg 1 --target-x -0.005 --target-z -0.075
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
import sys
import tempfile
import time
import xml.etree.ElementTree as ET

import numpy as np

try:
  import mujoco
  import mujoco.viewer
except ImportError as exc:
  raise SystemExit(
    "MuJoCo is required. Run this script from the project's MuJoCo/MJLab "
    "environment."
  ) from exc


try:
  from microtaur_velocity.microtaur_constants import (
    MICROTAUR_XML,
    MICROTAUR_STAND_A_OFFSETS,
    MICROTAUR_STAND_E_OFFSETS,
  )
  from microtaur_velocity.microtaur_kinematics import (
    FOOT_LATERAL_OFFSETS_M,
    FOOT_LATERAL_OFFSETS_M,
    FULL_JOINT_NAMES,
    HIP_MIDPOINTS_ROOT_M,
    MOTOR_JOINT_NAMES,
    MicrotaurFiveBarKinematics,
  )
except ImportError:
  # Permit placing this replay next to microtaur_kinematics.py.
  local_dir = Path(__file__).resolve().parent
  if str(local_dir) not in sys.path:
    sys.path.insert(0, str(local_dir))

  from microtaur_kinematics import (  # type: ignore
    FULL_JOINT_NAMES,
    HIP_MIDPOINTS_ROOT_M,
    MOTOR_JOINT_NAMES,
    MicrotaurFiveBarKinematics,
  )

  MICROTAUR_XML = None
  MICROTAUR_STAND_A_OFFSETS = (0.45, -0.45, -0.45, 0.45)
  MICROTAUR_STAND_E_OFFSETS = (-0.45, 0.45, 0.45, -0.45)


XL330_TABLE = {
  3.7: (0.42, 76.0),
  5.0: (0.52, 103.0),
  6.0: (0.60, 123.0),
}


def parse_args() -> argparse.Namespace:
  parser = argparse.ArgumentParser(
    description="Fixed-base Microtaur five-bar IK replay."
  )
  parser.add_argument(
    "--xml",
    type=Path,
    default=Path(MICROTAUR_XML) if MICROTAUR_XML is not None else None,
    help="Path to robot_modified.xml.",
  )
  parser.add_argument("--leg", type=int, choices=(1, 2, 3, 4), default=1)
  parser.add_argument(
    "--root-z",
    type=float,
    default=0.20,
    help="Fixed battery/root height in world metres.",
  )
  parser.add_argument(
    "--target-x",
    type=float,
    default=None,
    help="Static target x in the selected leg's hip-midpoint frame.",
  )
  parser.add_argument(
    "--target-z",
    type=float,
    default=None,
    help="Static target z in the selected leg's hip-midpoint frame.",
  )
  parser.add_argument("--amp-x", type=float, default=0.008)
  parser.add_argument("--amp-z", type=float, default=0.006)
  parser.add_argument("--frequency", type=float, default=0.25)
  parser.add_argument("--target-radius", type=float, default=0.007)
  parser.add_argument("--voltage", type=float, choices=(3.7, 5.0, 6.0), default=5.0)
  parser.add_argument("--kp", type=float, default=1.0)
  parser.add_argument("--kd", type=float, default=0.045)
  parser.add_argument(
    "--kinematic",
    action="store_true",
    help="Directly interpolate qpos instead of applying motor torque.",
  )
  parser.add_argument(
    "--kinematic-gain",
    type=float,
    default=1.0,
    help=(
      "Retained for command-line compatibility. Exact kinematic mode writes "
      "the complete analytical (a,b,e,d) solution each frame so equality "
      "closure is preserved; the value is not used."
    ),
  )
  parser.add_argument(
    "--no-realtime",
    action="store_true",
    help="Run as fast as possible.",
  )
  args = parser.parse_args()

  if args.xml is None:
    parser.error(
      "--xml is required when microtaur_velocity.microtaur_constants "
      "cannot be imported."
    )
  if (args.target_x is None) != (args.target_z is None):
    parser.error("--target-x and --target-z must be supplied together.")
  return args


def make_model(
  xml_path: Path,
  target_radius: float,
) -> tuple[mujoco.MjModel, mujoco.MjData]:
  """Load a temporary modified XML beside the source XML.

  The previous assets-dictionary loader created duplicate VFS basenames on
  Windows. Keeping the temporary XML beside the original lets MuJoCo resolve
  ``meshdir`` and relative asset paths directly from disk.
  """
  xml_text = xml_path.read_text(encoding="utf-8")
  target_body = f"""
    <body name="ik_target_marker" mocap="true" pos="0 0 0">
      <geom name="ik_target_green"
            type="sphere"
            size="{float(target_radius):.9f}"
            rgba="0 1 0 0.85"
            contype="0"
            conaffinity="0"
            group="0"/>
    </body>
  """

  if "</worldbody>" not in xml_text:
    raise ValueError("XML does not contain </worldbody>.")

  xml_text = xml_text.replace(
    "</worldbody>",
    target_body + "\n  </worldbody>",
    1,
  )

  temporary_path: Path | None = None
  try:
    with tempfile.NamedTemporaryFile(
      mode="w",
      suffix=".xml",
      prefix="microtaur_ik_replay_",
      dir=xml_path.parent,
      delete=False,
      encoding="utf-8",
      newline="\n",
    ) as temporary_file:
      temporary_file.write(xml_text)
      temporary_path = Path(temporary_file.name)

    model = mujoco.MjModel.from_xml_path(str(temporary_path))
  finally:
    if temporary_path is not None:
      try:
        temporary_path.unlink(missing_ok=True)
      except OSError:
        pass

  model.opt.gravity[:] = 0.0
  data = mujoco.MjData(model)
  return model, data


def joint_addresses(
  model: mujoco.MjModel,
  names: tuple[str, ...],
) -> tuple[np.ndarray, np.ndarray]:
  qpos = []
  dof = []
  for name in names:
    joint_id = mujoco.mj_name2id(
      model,
      mujoco.mjtObj.mjOBJ_JOINT,
      name,
    )
    if joint_id < 0:
      raise KeyError(f"Joint not found: {name}")
    qpos.append(int(model.jnt_qposadr[joint_id]))
    dof.append(int(model.jnt_dofadr[joint_id]))
  return np.asarray(qpos, dtype=np.int32), np.asarray(dof, dtype=np.int32)


def set_initial_closed_chain_state(
  model: mujoco.MjModel,
  data: mujoco.MjData,
  kinematics: MicrotaurFiveBarKinematics,
  root_position: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
  full_qpos_adr, full_dof_adr = joint_addresses(model, FULL_JOINT_NAMES)

  free_id = mujoco.mj_name2id(
    model,
    mujoco.mjtObj.mjOBJ_JOINT,
    "battery_freejoint",
  )
  if free_id < 0:
    raise KeyError("battery_freejoint was not found.")
  free_qpos_adr = int(model.jnt_qposadr[free_id])
  free_dof_adr = int(model.jnt_dofadr[free_id])

  data.qpos[free_qpos_adr : free_qpos_adr + 3] = root_position
  data.qpos[free_qpos_adr + 3 : free_qpos_adr + 7] = (
    1.0,
    0.0,
    0.0,
    0.0,
  )
  data.qvel[free_dof_adr : free_dof_adr + 6] = 0.0

  full_q = []
  for leg in range(4):
    solution = kinematics.forward_numpy(
      MICROTAUR_STAND_A_OFFSETS[leg],
      MICROTAUR_STAND_E_OFFSETS[leg],
      leg_index=leg + 1,
    )
    if not solution.valid:
      raise RuntimeError(f"Standing FK is invalid for leg {leg + 1}.")
    full_q.extend(solution.full.tolist())

  data.qpos[full_qpos_adr] = np.asarray(full_q, dtype=np.float64)
  data.qvel[full_dof_adr] = 0.0
  mujoco.mj_forward(model, data)
  return (
    np.asarray(
      [
        MICROTAUR_STAND_A_OFFSETS[i // 2]
        if i % 2 == 0
        else MICROTAUR_STAND_E_OFFSETS[i // 2]
        for i in range(8)
      ],
      dtype=np.float64,
    ),
    np.asarray(
      (
        free_qpos_adr,
        free_dof_adr,
      ),
      dtype=np.int32,
    ),
  )


def fix_root(
  data: mujoco.MjData,
  free_addresses: np.ndarray,
  root_position: np.ndarray,
) -> None:
  free_qpos_adr = int(free_addresses[0])
  free_dof_adr = int(free_addresses[1])
  data.qpos[free_qpos_adr : free_qpos_adr + 3] = root_position
  data.qpos[free_qpos_adr + 3 : free_qpos_adr + 7] = (
    1.0,
    0.0,
    0.0,
    0.0,
  )
  data.qvel[free_dof_adr : free_dof_adr + 6] = 0.0


def apply_xl330_torque(
  model: mujoco.MjModel,
  data: mujoco.MjData,
  motor_qpos_adr: np.ndarray,
  motor_dof_adr: np.ndarray,
  desired: np.ndarray,
  kp: float,
  kd: float,
  stall_torque: float,
  no_load_speed_rad_s: float,
) -> None:
  data.qfrc_applied[:] = 0.0

  for qadr, dadr, target in zip(
    motor_qpos_adr,
    motor_dof_adr,
    desired,
    strict=True,
  ):
    position = float(data.qpos[qadr])
    velocity = float(data.qvel[dadr])
    requested = float(kp) * (float(target) - position) - float(kd) * velocity

    upper = float(stall_torque) * (
      1.0 - velocity / float(no_load_speed_rad_s)
    )
    lower = float(stall_torque) * (
      -1.0 - velocity / float(no_load_speed_rad_s)
    )
    upper = min(upper, float(stall_torque))
    lower = max(lower, -float(stall_torque))

    if lower > upper:
      midpoint = 0.5 * (lower + upper)
      lower = midpoint
      upper = midpoint

    data.qfrc_applied[dadr] = np.clip(requested, lower, upper)


def main() -> None:
  args = parse_args()
  xml_path = args.xml.expanduser().resolve()
  if not xml_path.exists():
    raise FileNotFoundError(xml_path)

  kinematics = MicrotaurFiveBarKinematics()
  model, data = make_model(xml_path, args.target_radius)

  root_position = np.asarray((0.0, 0.0, args.root_z), dtype=np.float64)
  desired_motor, free_addresses = set_initial_closed_chain_state(
    model,
    data,
    kinematics,
    root_position,
  )

  motor_qpos_adr, motor_dof_adr = joint_addresses(
    model,
    MOTOR_JOINT_NAMES,
  )
  full_qpos_adr, full_dof_adr = joint_addresses(
    model,
    FULL_JOINT_NAMES,
  )

  target_body_id = mujoco.mj_name2id(
    model,
    mujoco.mjtObj.mjOBJ_BODY,
    "ik_target_marker",
  )
  if target_body_id < 0:
    raise KeyError("ik_target_marker was not created.")
  mocap_id = int(model.body_mocapid[target_body_id])
  if mocap_id < 0:
    raise RuntimeError("Target marker is not a mocap body.")

  foot_site_name = f"leg{args.leg}_foot_site"
  foot_site_id = mujoco.mj_name2id(
    model,
    mujoco.mjtObj.mjOBJ_SITE,
    foot_site_name,
  )
  if foot_site_id < 0:
    raise KeyError(foot_site_name)

  closure_site_1 = mujoco.mj_name2id(
    model,
    mujoco.mjtObj.mjOBJ_SITE,
    f"closing_leg{args.leg}_c_joint_1",
  )
  closure_site_2 = mujoco.mj_name2id(
    model,
    mujoco.mjtObj.mjOBJ_SITE,
    f"closing_leg{args.leg}_c_joint_2",
  )
  closure_site_1_z = mujoco.mj_name2id(
    model,
    mujoco.mjtObj.mjOBJ_SITE,
    f"closing_leg{args.leg}_c_joint_1_z",
  )
  closure_site_2_z = mujoco.mj_name2id(
    model,
    mujoco.mjtObj.mjOBJ_SITE,
    f"closing_leg{args.leg}_c_joint_2_z",
  )
  if min(
    closure_site_1,
    closure_site_2,
    closure_site_1_z,
    closure_site_2_z,
  ) < 0:
    raise KeyError(f"Closure sites for leg {args.leg} were not found.")

  selected = args.leg - 1
  standing_solution = kinematics.forward_numpy(
    MICROTAUR_STAND_A_OFFSETS[selected],
    MICROTAUR_STAND_E_OFFSETS[selected],
    leg_index=args.leg,
  )
  center = standing_solution.foot.copy()
  previous_motor = standing_solution.motor.copy()

  stall_torque, no_load_rpm = XL330_TABLE[float(args.voltage)]
  no_load_speed = no_load_rpm * 2.0 * math.pi / 60.0

  print(
    f"Leg {args.leg} nominal foot in hip frame: "
    f"x={center[0]:+.6f} m, z={center[1]:+.6f} m"
  )
  print(
    "Target is shown by the green sphere. "
    "The existing red foot collision sphere is the actual foot."
  )
  print(
    f"Applied fixed outboard foot offset: "
    f"{1000.0 * FOOT_LATERAL_OFFSETS_M[selected]:+.1f} mm in root y."
  )
  print(
    f"Mode: {'kinematic' if args.kinematic else 'XL330 torque-speed PD'}"
  )

  start_wall = time.perf_counter()
  last_print = start_wall

  with mujoco.viewer.launch_passive(model, data) as viewer:
    viewer.cam.distance = 0.45
    viewer.cam.azimuth = 130.0
    viewer.cam.elevation = -18.0
    viewer.cam.lookat[:] = root_position

    try:
      viewer.opt.geomgroup[:] = 1
      viewer.opt.sitegroup[:] = 1

      # The XML's closing_*_z sites sit 0.1 m away from each closure point and
      # are only equality-constraint orientation helpers.  They share site
      # group 3, so hide that group in replay.  The red actual-foot marker is a
      # geom and remains visible.
      if len(viewer.opt.sitegroup) > 3:
        viewer.opt.sitegroup[3] = 0
    except Exception:
      pass

    while viewer.is_running():
      frame_start = time.perf_counter()
      elapsed = frame_start - start_wall

      if args.target_x is not None:
        target_xz = np.asarray(
          (args.target_x, args.target_z),
          dtype=np.float64,
        )
      else:
        phase = 2.0 * math.pi * float(args.frequency) * elapsed
        target_xz = center + np.asarray(
          (
            float(args.amp_x) * math.sin(phase),
            float(args.amp_z) * math.sin(2.0 * phase),
          ),
          dtype=np.float64,
        )

      solution = kinematics.inverse_numpy(
        target_xz[0],
        target_xz[1],
        leg_index=args.leg,
        reference_motor=previous_motor,
      )
      if solution.valid:
        previous_motor = solution.motor
        motor_offset = 2 * selected
        desired_motor[motor_offset : motor_offset + 2] = solution.motor

      hip = HIP_MIDPOINTS_ROOT_M[selected]
      # The five-bar solver is planar in x-z, but the physical linkage is
      # layered 7 mm outboard from the actuator-center plane.  Apply that fixed
      # lateral offset when converting the planar IK target to world space.
      target_world = root_position + np.asarray(
        (
          hip[0] + target_xz[0],
          hip[1] + FOOT_LATERAL_OFFSETS_M[selected],
          hip[2] + target_xz[1],
        ),
        dtype=np.float64,
      )
      data.mocap_pos[mocap_id] = target_world
      data.mocap_quat[mocap_id] = (1.0, 0.0, 0.0, 0.0)

      fix_root(data, free_addresses, root_position)

      if args.kinematic:
        # A MuJoCo equality constraint is not a positional IK projector.
        # Directly changing only q_a/q_e and then calling mj_forward leaves the
        # passive q_b/q_d coordinates at their old values, so the two closure
        # branches separate.  Write the complete analytical state instead.
        #
        # The moving Cartesian target is already smooth, so the solved
        # (q_a,q_b,q_e,q_d) sequence is smooth without joint-space
        # interpolation.  Interpolating generalized coordinates between two
        # closed-chain states would itself leave the nonlinear constraint
        # manifold.
        if solution.valid:
          leg_slice = slice(4 * selected, 4 * selected + 4)
          selected_full_qpos = full_qpos_adr[leg_slice]
          selected_full_dof = full_dof_adr[leg_slice]
          data.qpos[selected_full_qpos] = solution.full
          data.qvel[selected_full_dof] = 0.0

        # Keep every motor velocity zero in this geometry-only mode.
        data.qvel[motor_dof_adr] = 0.0
        mujoco.mj_forward(model, data)
        data.time += model.opt.timestep
      else:
        apply_xl330_torque(
          model,
          data,
          motor_qpos_adr,
          motor_dof_adr,
          desired_motor,
          kp=args.kp,
          kd=args.kd,
          stall_torque=stall_torque,
          no_load_speed_rad_s=no_load_speed,
        )
        mujoco.mj_step(model, data)
        fix_root(data, free_addresses, root_position)
        mujoco.mj_forward(model, data)

      actual_world = np.asarray(data.site_xpos[foot_site_id]).copy()
      error = float(np.linalg.norm(actual_world - target_world))

      closure_error = max(
        float(
          np.linalg.norm(
            data.site_xpos[closure_site_1]
            - data.site_xpos[closure_site_2]
          )
        ),
        float(
          np.linalg.norm(
            data.site_xpos[closure_site_1_z]
            - data.site_xpos[closure_site_2_z]
          )
        ),
      )

      if frame_start - last_print >= 0.5:
        motor_offset = 2 * selected
        actual_motor = data.qpos[
          motor_qpos_adr[motor_offset : motor_offset + 2]
        ]
        print(
          f"target_xz=({target_xz[0]:+.4f}, {target_xz[1]:+.4f})  "
          f"q_des=({desired_motor[motor_offset]:+.3f}, "
          f"{desired_motor[motor_offset + 1]:+.3f})  "
          f"q=({actual_motor[0]:+.3f}, {actual_motor[1]:+.3f})  "
          f"foot_error={1000.0 * error:5.2f} mm  "
          f"closure_error={1000.0 * closure_error:7.4f} mm",
          end="\r",
          flush=True,
        )
        last_print = frame_start

      viewer.sync()

      if not args.no_realtime:
        remaining = model.opt.timestep - (
          time.perf_counter() - frame_start
        )
        if remaining > 0.0:
          time.sleep(remaining)

  print()


if __name__ == "__main__":
  main()